### ISSUE TITLE
Question ⁉️

### ISSUE THREAD

**Issue by Yet-another-NPC-guy** [auag0/DisableAudioFocus#1]
Module works perfectly fine on Miui 12.5.3 android 10 but you know how can I adjust per app volume control? I can't find an app to do it. Media volume it's the same for all apps and I know that the module function only consists on allow multiple audio srouces at the same time but maybe you know an app that can adjust different volume values for each app.

Thanks for your work 😊

**Comment by auag0** [comment]
its maybe hard, but i can try it in free time!!
and thank you for reaction

**Comment by Yet-another-NPC-guy** [comment]
> its maybe hard, but i can try it in free time!!
> and thank you for reaction

Bro I found audiohq magisk module, it gives the binaries and app to adjust volume for each app. With your module and audiohq it's like have sound assistant of miu based on android 11+ but on android 10. The problem it's that audiohq doesn't has a properly enforcing support, by default module changes selinux to permissive because on enforcing volume adjust has latency and can generate bootloop.

**Comment by Yet-another-NPC-guy** [comment]
> > its maybe hard, but i can try it in free time!!
> > and thank you for reaction
> 
> Bro I found audiohq magisk module, it gives the binaries and app to adjust volume for each app. With your module and audiohq it's like have sound assistant of miu based on android 11+ but on android 10. The problem it's that audiohq doesn't has a properly enforcing support, by default module changes selinux to permissive because on enforcing volume adjust has latency and can generate bootloop.

https://github.com/Alcatraz323/audiohq_module

**Comment by FahadBinHussain** [comment]
> > its maybe hard, but i can try it in free time!!
> > and thank you for reaction
> 
> Bro I found audiohq magisk module, it gives the binaries and app to adjust volume for each app. With your module and audiohq it's like have sound assistant of miu based on android 11+ but on android 10. The problem it's that audiohq doesn't has a properly enforcing support, by default module changes selinux to permissive because on enforcing volume adjust has latency and can generate bootloop.

hi, i had a similar question. is there a module/app/tool that allows background playback for any app?
